export enum NOTIFICATION_MUTATION_TYPES {
  TRIGGER_ERROR = "@NOTIFICATION/SET_ERROR",
  TRIGGER_SUCCESS = "@NOTIFICATION/TRIGGER_SUCCESS",
  HIDE = "@NOTIFICATION/HIDE",
  REFRESH = "@NOTIFICATION/REFRESH"
}
