export enum BEERS_MUTATION_TYPES {
  GET_BEERS_INITIAL_REQUESTED = "@BEERS/GET_BEERS_INITIAL_REQUESTED",
  GET_BEERS_INITIAL_SUCCEED = "@BEERS/GET_BEERS_INITIAL_SUCCEED",
  GET_BEERS_INITIAL_FAILED = "@BEERS/GET_BEERS_INITIAL_FAILED",
  GET_BEERS_NEXT_REQUESTED = "@BEERS/GET_BEERS_NEXT_REQUESTED",
  GET_BEERS_NEXT_SUCCEED = "@BEERS/GET_BEERS_NEXT_SUCCEED",
  GET_BEERS_NEXT_FAILED = "@BEERS/GET_BEERS_NEXT_FAILED"
}
